### ISSUE TITLE
Border flickering on resizing

### ISSUE THREAD

**Issue by husker-dev** [husker-dev/openglfx#1]
If the user has a large screen resolution or weak hardware, then flickering appears when the window is resized. 
It's not very noticeable on FullHD monitors.

(Screenshot captured on 4K monitor)
![image](https://user-images.githubusercontent.com/31825139/128785655-86b75ab4-8576-401a-bad7-f8cb5e3aff2a.png)

**Comment by husker-dev** [comment]
This problem occurs because of compatibility with all devices, so the rendering algorithm looks like this:

```GL frame buffer``` -> ```IntBuffer``` -> ```PixelBuffer``` -> ```WritableImage``` -> _```Window surface```_

The main problem here with the **WritableImage** - it takes a lot of time to create and show
Also **ImageView**'s properties **fitWidth** and **fitHeight** can't handle size difference as quickly as needed.


---
There is a way to avoid unnecessary steps, and turn the algorithm into the following:

```GL frame buffer``` -> _```Window surface```_

(An example is in the [mojtab23/jfxgl](https://github.com/mojtab23/jfxgl) repository)

But the problem is that JavaFX uses different tools to render the image to the window. **Direct3D** for Windows, **OpenGL** for Linux and MacOS. Software Java2D is also used if none of the tools are available.

_(Maybe I misunderstand the JavaFX rendering system)_

---
So, there is no universal way to render content directly to the surface of a window.

**Comment by husker-dev** [comment]
In the current version of OpenGLFX flickering is fixed by optimization

**Comment by lqyaos** [comment]
Hello, I am now using jogl2.4 to implement NewtCanvasJFX. It provides a native window. I feel that this performance is the highest. I want to share with you and ask about the performance of this solution.

https://github.com/tpetrychyn/dockfx-newtcanvasjfx-example

**Comment by husker-dev** [comment]
Newt windows itself are cool, but mixing it with JavaFX is not the best idea.

I see several problems in using Newt as NewtCanvasJFX:
- It's just a "glued" window to main JavaFX one, so you can't draw/show elements over it
- Doesn't have HiDPI support
- Bad performance when resize (It's not flickering, but lagging)
- Large code for simple demo

> When I looked into JavaFX's OpenGL implementations, this was the first thing I saw. It is not very bad, but it has some flaws that were critical in my application. So I decided to get rid of them in my OpenGLFX library

Here is 100% NewtCanvasJFX size on windows 1.75 scale:


![image](https://user-images.githubusercontent.com/31825139/149909661-af80e54c-f8d8-468e-a682-c18c37c5e6a8.png)

**Comment by lqyaos** [comment]
I'm a little bit clueless about HiDPI, can I do it by adjusting the width and height? If I don't care about the resize lag, don't I need to consider HiDPI?

**Comment by husker-dev** [comment]
Yes, you can fix it by multiplying height and width by screen DPI.

Also you need to increase the size by 1px to remove the empty border (I think it has to do with floating-point calculation errors).

![image](https://user-images.githubusercontent.com/31825139/149923308-1d7b02c1-8a6d-4f67-bc8d-39fc14286566.png)

For example in Kotlin
```kotlin
scene.widthProperty().addListener { _, _, _ ->
    canvas.widthProperty().set(canvas.width * scene.window.outputScaleX + 1)
}
scene.heightProperty().addListener { _, _, _ ->
    canvas.heightProperty().set(canvas.height * scene.window.outputScaleX + 1)
}
```




Resizing lag and HiDPI are not related. So, I recommend you to implement this fix anyway for better application support.

**Comment by lqyaos** [comment]
Yes, it is finally high enough to start business development, thank you for your support
