### ISSUE TITLE
Suggest renaming OpenGLCanvas#createTimer()

### ISSUE THREAD

**Issue by orange451** [husker-dev/openglfx#11]
The method name and input param seem to conflict with each-other. Normally when creating timers you specify the time in between each iteration. Whereas this is specifying the desired FPS.

Might I suggest renaming this method to
OpenGLCanvas#setDesiredRefreshRate()

Also is there a way to unlimit the fps? No documentation that I can find currently (I don't think many of the methods have documentation)

**Comment by orange451** [comment]
In fact the timer concept is quite confusing.
createTimer() also seems to have the effect of applying the timer to the object containing the method. I think that's a pretty confusing API design for a public-facing API.

**Comment by orange451** [comment]
To keep in the spirit of JavaFX, perhaps make the public facing api use a two-way bind variable?

**Comment by husker-dev** [comment]
Yes, the Timer was created "just to be". 
In the future, I want to fully remake it.

**Comment by husker-dev** [comment]
I redesigned the Timer class. Now it’s called Animator. See the readme for details
