### ISSUE TITLE
How to use INCLUDE_ES2 for Maven

### ISSUE THREAD

**Issue by orange451** [husker-dev/openglfx#12]
I want to use direct rendering with LWJGL using the supplied jar file:
[javafx.graphics.win-es2.jar](https://github.com/husker-dev/openglfx/blob/master/libs/javafx.graphics.win-es2.jar)

How can this be accomplished?

**Comment by husker-dev** [comment]
To use [javafx.graphics.win-es2.jar](https://github.com/husker-dev/openglfx/blob/master/libs/javafx.graphics.win-es2.jar) just add it to your Maven dependency as a regular .jar file library.

About INCLUDE_ES2
---
INCLUDE_ES2 is a [property](https://github.com/openjdk/jfx/blob/d69a498c2cde73339bc99e6c02c0d47fe4b1b650/build.gradle#L493) for JavaFX build.gradle script that allows to compile JavaFX sources including OpenGL pipeline for Windows.

After setting this property to true, output files will include ```javafx.graphics.win-es2.jar```
