### ISSUE TITLE
Suggestion: Add OpenGLCanvas#runLater(Runnable)

### ISSUE THREAD

**Issue by orange451** [husker-dev/openglfx#13]
JavaFX has a convenient way to defer a code execution until the next time JavaFX thread is unyielded using Platform#runLater().
I think an OpenGLCanvas#runLater(Runnable) method would be beneficial to defer code execution until the canvas will next render.

**Comment by husker-dev** [comment]
Why is this necessary?
If this method exists, it will be executed at the moment of rendering. For this situations there are already methods onDraw or onUpdate.

**Comment by orange451** [comment]
Like I said, as a means to defer rendering code from another thread. This way I can force synchronization with a specific node element.

You are right, that it isn't necessary, just convenient.

**Comment by husker-dev** [comment]
I don’t think this will be helpful, so I’ll close issue
