### ISSUE TITLE
Suggest rename OpenGLCanvas#onReshape()

### ISSUE THREAD

**Issue by orange451** [husker-dev/openglfx#15]
the method name onReshape for OpenGLCanvas is a little awkward. The shape could be considered as either dimensions of the existing shape, or a literal shape (oval, square, rectangle, triangle, etc). The shape will always be a rectangle, but the dimensions can change. Perhaps rename to OpenGLCanvas#onSizeChange()?

Or the user could just bind to the widthproperty/heightproperty that JavaFX already provides for us as this is a member of the Region class, which makes a size change callback redundant.

**Comment by husker-dev** [comment]
See #14
