### ISSUE TITLE
LWJGL Running From Jar (UnsatisfiedLinkError)

### ISSUE THREAD

**Issue by orange451** [husker-dev/openglfx#16]
When packaging a FAT jar containing all of my libraries, I cannot execute using `java -jar` CLI method.

```
java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib
	at org.lwjgl.system.Library.loadSystem(Library.java:164)
	at org.lwjgl.system.Library.loadSystem(Library.java:63)
	at org.lwjgl.system.Library.<clinit>(Library.java:51)
	at org.lwjgl.opengl.GL.<clinit>(GL.java:80)
	at com.huskerdev.openglfx.lwjgl.direct.LWJGLDirect.onNGRender(LWJGLDirect.kt:36)
	at com.huskerdev.openglfx.OpenGLCanvas$NGOpenGLCanvas.renderContent(OpenGLCanvas.kt:138)
```

The files required should be in the jar file though:

<img width="899" alt="Screen Shot 2022-04-30 at 9 03 08 PM" src="https://user-images.githubusercontent.com/5247778/166127760-b1f1d2e9-74fe-444f-b24a-98f8f7d82db0.png">

**Comment by orange451** [comment]
I am packaging the far jar using:
```
<!-- FAT Jar (mvn clean package) -->
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-assembly-plugin</artifactId>
	<version>3.1.1</version>
	<configuration>
		<descriptorRefs>
			<descriptorRef>jar-with-dependencies</descriptorRef>
		</descriptorRefs>
		<archive>
			<manifest>
				<mainClass>dev.anarchy.Main</mainClass>
			</manifest>
		</archive>
	</configuration>
	<executions>
		<execution>
			<id>make-assembly</id>
			<phase>package</phase>
			<goals>
				<goal>single</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

**Comment by orange451** [comment]
Repro:
https://github.com/orange451/OpenGLFX-LWJGL-Sample

**Comment by orange451** [comment]
If you feel this is not relevant to your project, let me know! If that's the case, I'll ask on LWJGL repo

**Comment by husker-dev** [comment]
I don’t think it is related to my project. 
It doesn’t contain lwjgl library code or files

**Comment by orange451** [comment]
I will do some more digging and post the solution here if I find it.

**Comment by husker-dev** [comment]
I will close this issue as it is not really related to openglfx. You can reopen if needed
