### ISSUE TITLE
Strange transparency behavior

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [husker-dev/openglfx#28]
```
glClearColor(0, 0, 0, 0)
glClear()
```

 gives white not black. You can reproduce it with [the example]( https://github.com/husker-dev/openglfx/pull/29/commits/63684b04056bc2c315ee5512d2b41ac138369ed6#diff-90fc783d2e2ba412eab1c5ae21fa6f5c20aa1996893fddc99a59c7d99c1b04d7)

**Comment by husker-dev** [comment]
You set the color to completely transparent black.  This means that no pixels will literally change.  
The background color will be the same as the background color of the parent component.

My advice to you is to try using OpenGL separately from openglfx first.
