### ISSUE TITLE
A third OpenGL binding for OpenGLFX?

### ISSUE THREAD

**Issue by jzy3d** [husker-dev/openglfx#31]
I use new tools from Oracle to produce native OpenGL bindings easily. The whole is much easier to build than historical frameworks like JOGL and LWJGL. As it covers Swing and more recently JavaFX, I thought you would be interested in integrating it in DriftFX.

There's a simple demo [here](https://gitlab.com/jzy3d/panama-gl/-/blob/main/panama-gl-ui-javafx/src/test/java/demos/panamagl/javafx/DemoTeapot_Onscreen_JavaFX.java). Using such a sample requires the below dependency 

```xml
<dependency>
	<groupId>org.jzy3d</groupId>
	<artifactId>panama-gl-ui-javafx</artifactId>
	<version>${project.version}</version>
</dependency>
```
 
It is made available on Jzy3D's maven server here : 

```xml
<repositories>
  <repository>
    <id>jzy3d-snapshots</id>
    <name>Jzy3d Snapshots</name>
    <url>https://maven.jzy3d.org/snapshots/</url>
  </repository>
  <repository>
    <id>jzy3d-releases</id>
    <name>Jzy3d Releases</name>
    <url>https://maven.jzy3d.org/releases/</url>
  </repository>
</repositories>
```

I'll be happy to answer question on this discussion.

**Comment by husker-dev** [comment]
Hi,

A third OpenGL binding would be a nice new feature to this project. Unfortunately now I have not ability to use something better than smartphone. So you can try to create it by yourself by implementing [this](https://github.com/husker-dev/openglfx/blob/master/core/src/main/kotlin/com/huskerdev/openglfx/core/GLExecutor.kt) class, like lwjgl and jogl modules does:
https://github.com/husker-dev/openglfx/blob/master/jogl/src/main/kotlin/com/huskerdev/openglfx/jogl/JOGLFXExecutor.kt

https://github.com/husker-dev/openglfx/blob/master/lwjgl/src/main/kotlin/com/huskerdev/openglfx/lwjgl/LWJGLExecutor.kt

> I’m planning to make big changes in library this summer, so you can just wait for it :)
