### ISSUE TITLE
Use of GL3ES3

### ISSUE THREAD

**Issue by detsikas** [husker-dev/openglfx#38]
Hi.
I was wondering, what it would take to use GL3ES3, In particular, I have a lot of OpenGL ES3, I tried to make changes to the library for using GL3ES3, but I have a problem with framebuffers an cannot render to and then read from a framebuffer.

Thank you,
Nikos

**Comment by husker-dev** [comment]
Hi!
I would like to ask you the following:
1. Your OS name;
2. Java and JavaFX version;
3.  OpenGL version from ```glGetIntegerv(GL_MAJOR_VERSION)``` and ```glGetIntegerv(GL_MINOR_VERSION)```;
4. What GL library you are using (jogl or lwjgl).

**Comment by detsikas** [comment]
I am using

1. Ubuntu 22.04, but I will also run the app on windows and MacOS
2.openjdk 20 and JavaFX 20.0.1
3. MAJOR 4, MINOR 6
4. I am using JOGL

**Comment by detsikas** [comment]
Thank you for the warning. I will certainly consider it.
I will share code, but I think I should first explain better what I did.
First of all, I need an opengl canvas in a JavaFX gui and since there is non in JavaFX, I came across openglfx.

What I am doing is applying opengl filtering on images. There is no 3D rendering.
When I use only one shader everything works perfect. When more shaders are needed, where one renders to a framebuffer which the next one uses as input, nothing is rendered.

All the opengl code works wihtout any changes when I render to a GLCanvas. The code also works on Android, without any changes.

But it does not work with openglfx. To begin with, in order to use OpenGL ES3, I did some modifications to the opengl fx (I believe the Apache license allows for that). My opengl knowledge is not too deep so I merely did changes of the form os replacing GL  with GL3ES3. It actually works to the extent that I have described.

To give another hint of what is different compared to GLCanvas and Android, when I create a texture and bind it to a framebuffer, the ids returned are numbers like 36, 40 etc, while in GLCanvas and Android I get ids like 1 and 2. This looks like an indication that something is different there.

I hope I described better. If any of there help you give me a hint as to what I have forgotten to port to GL3ES3 I will be happy.

Otherwise, I can share the openglfx modifications.

Best regards,
Nikos

**Comment by husker-dev** [comment]
In your case, the modification to use GL3ES3 was unnecessary, since JOGL has a function that converts objects from one version of OpenGL to another:
```java
gl2 = gl.getGL2();
gl3 = gl.getGL3();
// And probably there is something like this
gl3es2 = gl.getGL3ES3();
```

---
You can try to test the code independenly from openglfx, for example on pure lwjgl. 
It looks like it's not a problem with openglfx itself.

The difference in texture ids is not important, but I explain it below.

---
> **DETAILS**
> In your case (Linux) openglfx will render into JavaFX frame using 'shared contexts'. It will bind the OpenGL context on which JavaFX renders the interface to your new context. This means that FBO can have consecutive id's. This gives a way to display custom opengl in javafx (what openglfx library does).
> If 20 FBO were created somewhere in the JavaFX context, then in your context the id of the first FBO will be 21. 
> It doesn't matter for rendering itself, as the OpenGL spec says IDs can be random at all. 
> Also, it does not affect the use of FBO.

**Comment by detsikas** [comment]
I reverted the changes and used openglfx as is and got GL3ES3 as you suggested, but still no change.

I would insist on the framebuffer index issue, not as an error, but as an indication that I am taking a different path to opengl when using openglfx as to the one when I am using jogl directly.

In any case, for now I will not pursue this problem any more.

I am very grateful for the help! 

Best regards,
Nikos

**Comment by detsikas** [comment]
Hi again,

I am reopening the issue to report an update. If I force universal, I do get the "normal" texture id and framebuffer numbering (i.e 1,2,3 etc).

I cannot see if the second shader actually does something because it crashes at the first rendring call. I am adding the top of the crash stack

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.sun.prism.es2.GLContext.nDrawIndexedQuads(JI[F[B)V+0 javafx.graphics@20
j  com.sun.prism.es2.GLContext.drawIndexedQuads([F[BI)V+7 javafx.graphics@20
j  com.sun.prism.es2.ES2Context.renderQuads([F[BI)V+7 javafx.graphics@20
j  com.sun.prism.impl.BaseContext.drawQuads([F[BI)V+8 javafx.graphics@20
j  com.sun.prism.impl.VertexBuffer.flush()V+23 javafx.graphics@20
j  com.sun.prism.impl.BaseContext.flushVertexBuffer()V+12 javafx.graphics@20
j  com.sun.prism.impl.ps.BaseShaderContext.checkState(Lcom/sun/prism/impl/ps/BaseShaderGraphics;ILcom/sun/javafx/geom/transform/BaseTransform;Lcom/sun/prism/ps/Shader;)V+32 javafx.graphics@20
j  com.sun.prism.impl.ps.BaseShaderContext.validateTextureOp(Lcom/sun/prism/impl/ps/BaseShaderGraphics;Lcom/sun/javafx/geom/transform/BaseTransform;Lcom/sun/prism/Texture;Lcom/sun/prism/Texture;Lcom/sun/prism/PixelFormat;)Lcom/sun/prism/ps/Shader;+166 javafx.graphics@20
j  com.sun.prism.impl.ps.BaseShaderContext.validateTextureOp(Lcom/sun/prism/impl/BaseGraphics;Lcom/sun/javafx/geom/transform/BaseTransform;Lcom/sun/prism/Texture;Lcom/sun/prism/PixelFormat;)V+10 javafx.graphics@20

I have no idea what shared and universal modes are, but I was hoping that it could give you a hint as to what is going on with the buffers.

Nikos

**Comment by detsikas** [comment]
Thank you for the response. I deleted my message because it was again about numbering and after reading your previous answer it became clear that numbers like 35, 36 etc, probably occur because JavaFX creates buffers too. If this is the reason, I will no longer investigate in that direction.

I am not doing anything related to threads nor am I creating  new threads.

If I trace the code, all event code (renderEvent, reshapeEvent etc) is executed in QuantumRenderer-0 while the rest of the code in a JavaFXApplicationThread.

**Comment by husker-dev** [comment]
I will close this issue. If you have any questions, feel free to reopen it.
