### ISSUE TITLE
I want to implement a video editing software, is it appropriate to use this program? 

### ISSUE THREAD

**Issue by lqyaos** [husker-dev/openglfx#4]
I want to ask you a question: I want to implement a video editing software, is it appropriate to use this program? (Is there a performance problem) Do you want to use DirectGLRendereror UniversalRenderer

**Comment by husker-dev** [comment]
Hi.
JavaFX uses several "engines" to display content in a window.  These are DirectX, OpenGL and Software. 

The main problem with using JOGL or LWJGL is that OpenGL rendering is not enabled by default on Windows. This forces you to do some workarounds.

- UniversalGLRenderer draws into a buffer, which is then read into an image. And this is how it happens, each frame. This method works independently of the engine.

- DirectGLRenderer draws directly to the JavaFX window, as it does other components in window.

As you can see, the second method has a performance advantage. 
Therefore, I recommend using it.

Also, read [wiki](https://github.com/husker-dev/openglfx/wiki/How-to-use-OpenGL-on-Windows) article about OpenGL in windows.
