### ISSUE TITLE
Possibility to flip Y axis

### ISSUE THREAD

**Issue by qq1053831109** [husker-dev/openglfx#40]
The picture is reversed. It's best to rotate this here in openglfx

**Comment by husker-dev** [comment]
This is already implemented in the current version of the code, which is awaiting release in near future

**Comment by husker-dev** [comment]
Just a note how to use it:
```kotlin
val canvas = OpenGLCanvas.create(LWJGL_MODULE, flipY = true)
```
```flipY = false``` (default) is equal to simple OpenGL output as it made in GLFW.
So, ```flipY = true``` is equivalent to the current behaviour in version 3.0.5
