### ISSUE TITLE
do you know lwjgl2 opengl render to awt canvas principle？

### ISSUE THREAD

**Issue by qq1053831109** [husker-dev/openglfx#43]
do you know lwjgl2 opengl render to awt canvas principle？
why javafx cant use that principle?

**Comment by husker-dev** [comment]
I don't know how does lwjgl2 work. As far as I know, it is deprecataed.

I can say how does JOGL works on AWT/Swing. 
AWT/Swing uses two possible render types: **software** and **OpenGL**. 
- On software it just copies pixels from your OpenGL framebuffer into application surface.
- In case of OpenGL, it can use a lot of different approaches to send framebuffer from one context (your) to another (AWT/Swing application). The simpliest and better supported is context sharing. Contexts will have one common framebuffer. 

JavaFX has one more rendering type: DirectX9 (called d3d). It needs a third way to transmit information.
Also, if JavaFX will updates normally, a fourth rendering type will be added - Apple's Metal.

---

JavaFX itself does not support separate OpenGL rendering, although developers have wanted to add such a feature in the distant past.

**Comment by husker-dev** [comment]
I'll close this issue. If you have any questions, reopen it again.
