### ISSUE TITLE
Will multithreading synchronization cause Javafx to get stuck?

### ISSUE THREAD

**Issue by qq1053831109** [husker-dev/openglfx#54]
Is there a wait timeout for multithreaded rendering? If the timeout exceeds 30ms, the current frame will be discarded directly. This ensures that Javafx is running the process. The opengl thread may be loading a weight model or initializing a scene, etc. The main solution of multithreading is that getting stuck in Opengl will not cause Javafx to get stuck.

**Comment by qq1053831109** [comment]
I often get stuck while working on the game editor Opengl. I hope that at this point, Javafx won't get stuck to play the loaded animation

**Comment by qq1053831109** [comment]
![点击在独立游戏中测试](https://github.com/husker-dev/openglfx/assets/17372170/da939032-347e-4234-8cb1-3a01463d8ee0)

**Comment by qq1053831109** [comment]
![image](https://github.com/husker-dev/openglfx/assets/17372170/285cebdb-d59d-4006-b8dc-1479b9da02a9)

**Comment by husker-dev** [comment]
Asynchronous rendering is performed entirely on a separate thread. When the frame is ready, it asks JavaFX to display it. This operation can only affect UI performance if you are using Windows and your video card does not support NVDX_interop. 
There are no restrictions on frame time. When testing, I deliberately stopped the render thread for a few seconds, and it did not interfere with the main thread.

**Comment by qq1053831109** [comment]
ok i am update to 4.0. it has  a lot change。

**Comment by qq1053831109** [comment]
PassthroughShader parallelContext resultContext？Seems a bit troublesome? Are you sure this is the best solution? Is it not possible to switch between two FBOs in one context?

**Comment by qq1053831109** [comment]
private change to protected  。we need  hook by extends

**Comment by husker-dev** [comment]
I'm sure this is not the best solution. But it's working for now.

Let's figure it out: 
- we have GL context from JavaFX that we should not touch.
- we need to send FBO from another context, which is not possible with shared contexts, so we use textures and PasstroughShader.

---

What I do:
- Create GL context in a new thread.
- Create proxy GL context that is shared with JavaFX and our first context, to perform some GL stuff without touching JavaFX itself.

Rendering thread steps looks like this:
1. \*rendering*
2. Blit rendered data to temporary texture.
3. \*signals to JavaFX to redraw*

JavaFX steps:
1. \*gets signal from rendering thread*
2. Switching to proxy GL context
3. Copy temporary texture data to JavaFX texture using PassthroughShader
4. Switching back to JavaFX context
5. Render texture 

---

A little later I will remake this mechanism into something lighter and smaller.

**Comment by qq1053831109** [comment]
ok,I haven't thought of a better plan yet
