### ISSUE TITLE
Example Usage?

### ISSUE THREAD

**Issue by orange451** [husker-dev/openglfx#6]
Is there any hello world program utilizing this with Direct mode? Not really clear on what is the point of this is. OpenGLPane doesn't have much functionality?

**Comment by husker-dev** [comment]
- Looks like you didn't read readme.md. There are tabs at the [end of the file](https://github.com/husker-dev/openglfx#example-code) with usage of JOGL and LWJGL. There are also links to ```example``` module with simple OpenGL program. ([Here is](https://github.com/husker-dev/openglfx/blob/master/lwjgl/src/examples/kotlin/Direct.kt) Direct using LWJGL)

- Yes, OpenGLPane has similar functionality. But the last update was 5 years ago. A lot has changed in JavaFX... Also if you look into the implementation, you will see a huge amount of rewritten internal JavaFX ```prism``` classes, when my implementation fits in one small file.

> For better understanding of openglfx: 
> - Direct - enabled when JavaFX uses OpenGL as rendering pipeline (better performance)
> - Universal - all other cases
>
> You can read more [here](https://github.com/husker-dev/openglfx/wiki).

**Comment by orange451** [comment]
Might I suggest making that example module a little easier to find? That is exactly what I was looking for, but after 15 minutes of clicking around I didn't see it, and nearly moved away from this project.

**Comment by husker-dev** [comment]
I've moved the example module up a bit. Thank you for your interest in the project.
