### ISSUE TITLE
AsyncSharedGL has blurred screen！

### ISSUE THREAD

**Issue by qq1053831109** [husker-dev/openglfx#63]
![QQ图片20231129222909](https://github.com/husker-dev/openglfx/assets/17372170/0ded814f-d3b0-4375-b398-07eef5f6676a)

**Comment by qq1053831109** [comment]
it is 4.0.0 version.

**Comment by husker-dev** [comment]
Can you try to use at least 4.0.1 version? There were a lot of async canvas fixes.

Also, is the problem only with these artifacts, or are there other problems? 
Are you resizing these Canvas?

**Comment by husker-dev** [comment]
@qq1053831109 I can't help you without feedback

**Comment by qq1053831109** [comment]
the only happened on some laptops. The testing cycle is relatively long. It was submitted to me by my product user. My desktop computer won't have a splash screen. More feedback requires a longer cycle to obtain

**Comment by qq1053831109** [comment]
I will be using 4.03 in the next version and it is expected to take a month to receive feedback on whether to fix it

**Comment by qq1053831109** [comment]
More open public is needed, do not use internal. we need extends your class

**Comment by qq1053831109** [comment]
like javafx all pane in one javafx Thread. gl need in one Thread。not every gl panel has   independent thread.  I have 100 gl panels at the same time.The underlying layers are all in one libgdx thread

**Comment by husker-dev** [comment]
## Threads 
For a large amount of async GLCanvas having an independent thread is not good. I can make some kind of shared thread that can be applied to several GLCanvas. This way you can divide a large number of GLCanvas into groups and reduce the number of threads.

![image](https://github.com/husker-dev/openglfx/assets/31825139/9af70688-5806-41a2-977f-9d0a636b0e40)

## About LibGDX. 
Like regular OpenGL, it can run on different threads. I can't suggest anything without analyzing the application code. 
I [made a module](https://github.com/husker-dev/openglfx/tree/master/modules/libgdx/src/main/kotlin/com/huskerdev/openglfx/libgdx) for LibGDX, but it hasn't been tested yet.

**Comment by husker-dev** [comment]
Check the new release 4.1.0.
If the problem is not solved, then reopen the issue
