### ISSUE TITLE
Maven support without Jitpack

### ISSUE THREAD

**Issue by Lewinator56** [husker-dev/openglfx#7]
Simple as the title, this appears to be one of the few implementations of openGL in javafx that pretty much fits my needs for the application im developing, which is however not using koltin and uses maven and normal java source. Maybe i'm missing something to get this working however.

**Comment by husker-dev** [comment]
Thanks for your interest in my project!

The Kotlin library (kotlin-stdlib) does not require the use of Kotlin language itself. Therefore, it can be added to a regular Java project

Pure **Maven** support is planned for the near future. 
For now you can use JitPack in Maven:

```xml
<repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```
```xml
<dependency>
    <groupId>com.github.husker-dev.openglfx</groupId>
    <artifactId>core</artifactId>
    <version>2.5.1</version>
</dependency>
<dependency>
    <groupId>com.github.husker-dev.openglfx</groupId>
    <artifactId>lwjgl</artifactId>
    <version>2.5.1</version>
</dependency>

<dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-stdlib</artifactId>
    <version>1.6.10</version>
</dependency>
```

**Comment by Lewinator56** [comment]
thanks for getting back so quickly, now ive just got to get everything working

**Comment by husker-dev** [comment]
I will reopen the issue to leave a reminder to do Maven support without Jitpack

**Comment by husker-dev** [comment]
Finally, after 1.5 years, it is completed!

Will be available as Gradle or Maven dependency:
```groovy
implementation 'com.huskerdev:openglfx:3.1'
implementation 'com.huskerdev:openglfx-lwjgl:3.1'
implementation 'com.huskerdev:openglfx-jogl:3.1'
```
