### ISSUE TITLE
Alpha is abnormal.

### ISSUE THREAD

**Issue by DontingK** [husker-dev/openglfx#73]
**Describe the bug**
This is my test using openglfx on jmonkeyengine. 
The alpha looks incorrect and the font is a little blurry in the rendering. 
I don't know what caused it. 

[this is init jemrender to fx  ](https://github.com/DontingK/jme3-fx-awt/blob/master/fx-test/src/main/java/com/jme3/system/lwjgl/LwjglCanvas.java)
 canvas =new GLCanvas(LWJGL2Executor.LWJGL2_MODULE, GLProfile.Compatibility,false,samples,false);

**To Reproduce**

**Screenshots**
![image](https://github.com/husker-dev/openglfx/assets/49473469/c0ff5a9b-4e18-441a-b79d-6eb81c224d36)

**Environment:**
 - OS: [win10 22H2  19045.3570]
 - openglfx version: [4.0.5]

**Comment by DontingK** [comment]
> **Describe the bug** This is my test using openglfx on jmonkeyengine. The alpha looks incorrect and the font is a little blurry in the rendering. I don't know what caused it.
> 
> [this is init jemrender to fx ](https://github.com/DontingK/jme3-fx-awt/blob/master/fx-test/src/main/java/com/jme3/system/lwjgl/LwjglCanvas.java) canvas =new GLCanvas(LWJGL2Executor.LWJGL2_MODULE, GLProfile.Compatibility,false,samples,false);
> 
> **To Reproduce**
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/49473469/290980290-c0ff5a9b-4e18-441a-b79d-6eb81c224d36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MTQzODEsIm5iZiI6MTcwMjcxNDA4MSwicGF0aCI6Ii80OTQ3MzQ2OS8yOTA5ODAyOTAtYzBmZjVhOWItNGUxOC00NDFhLWI3OWQtNmViODFjMjI0ZDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA4MDgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YTkxYThlZmQ1ZjFiMzI3NjQwMzU2ZTc2OTMyYzY3Mjg2MDEyYTkyZThmNTFmNGI5ZGNmYTA2NGU3NDk5YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.McJHVCavnJCK7MoXWv4jdJP-8QJaPNVwmJnF3z4sM68)
> 
> **Environment:**
> 
> * OS: [win10 22H2  19045.3570]
> * openglfx version: [4.0.5]

Using the openglfx-lwjgl2:4.0.5

**Comment by husker-dev** [comment]
The blurry text looks as if the entire image is rendered 1-5 pixels smaller than needed, and then stretched to the window size.

I can’t say anything about incorrect alpha blending. openglfx does not directly interact with it, but only takes the pixels of the final image. There may be an incorrect pixel format - RGBA/RGBA_PRE.

Look this way.

**Comment by DontingK** [comment]
Is this the problem with the way I use it or the library itself. 
I'm not sure if it's my problem.

**Comment by husker-dev** [comment]
This doesn't look like a library problem. Check what I wrote above
