### ISSUE TITLE
NVidia NSight profiling

### ISSUE THREAD

**Issue by jodysowald** [husker-dev/openglfx#75]
**I have a question***
Is there any way to collect data with NVidia NSight while using OpenGLFX?

**Comment by husker-dev** [comment]
As I remember, NSight can only connect to DirectX and Vulkan

**Comment by jodysowald** [comment]
I have never used it before, but was given the advice, relative to working with OpenGL, that it can automatically give me performance profiling and comparison of multiple runs of the code. NSight does appear to have information collection for OpenGL looking at its front page
<img width="1376" alt="image" src="https://github.com/husker-dev/openglfx/assets/153639963/b062c832-3f9c-45bb-8b72-f687c0c5ca44">

**Comment by husker-dev** [comment]
I'll see how it can be used soon

**Comment by jodysowald** [comment]
Thank you!

**Comment by husker-dev** [comment]
Unfortunately, Nsight can only capture windows with a single rendering (created through glfw, for example). 
And since openglfx renders everything inside "offscreen" buffer and then glues the result to javaFX, this makes it impossible to catch.

---
Alternatively, you can use RenderDoc - it has support for such buffers. 
Look at the readme to enable it in openglfx.

**Comment by husker-dev** [comment]
Theoretically it is possible to create a "debug" mode, in which openglfx rendering will occur in a separate window. This will make it possible to use NSight

**Comment by yetyman** [comment]
Thank you!

**Comment by jodysowald** [comment]
Are there any plans for this?

**Comment by husker-dev** [comment]
Yes, progress is slow, but work is underway

**Comment by husker-dev** [comment]
I have rendered openglfx content into a separate window after showing in the canvas, and now RenderDoc and NSight see the application and let see details.

GLCanvas will have `externalWindow` field in constructor.

![image](https://github.com/user-attachments/assets/97b32dd7-23a6-42f3-915d-04cb77f17610)
![Снимок экрана 2024-12-01 175532](https://github.com/user-attachments/assets/acddc2b0-c086-4720-85a0-24c28801b501)

**Comment by yetyman** [comment]
That's awesome!

**Comment by husker-dev** [comment]
Added in release `4.1.0`. Check `README.md` for more information.

**Comment by yetyman** [comment]
Thanks for all these updates!
