### ISSUE TITLE
No rendered content on Mac OS without `async` option for GLCanvas

### ISSUE THREAD

**Issue by SoKnight** [husker-dev/openglfx#77]
**Describe the bug**
JavaFX window has no rendered content on Mac OS with OpenGLFX.
Setting up `async` option to `true` fixes this problem:
```java
new GLCanvas(LWJGLExecutor.LWJGL_MODULE, GLProfile.Core, false, 0, true /* set 'true' here */);
```

**Environment:**
 - OS: Mac OS Sonoma 14.1.1 (Apple M1)
 - openglfx version: 4.0.5

**Comment by husker-dev** [comment]
Fixed, because there is no longer a sync/async types
