### ISSUE TITLE
NPE when dispose

### ISSUE THREAD

**Issue by RealThanhpv** [husker-dev/openglfx#82]
**Describe the bug**
NPE when calling dispose. I am not so sure but It seems the animationTimer is still running after the canvas disposed. Or dispose() is not threadsafe

**To Reproduce**
```
canvas = new GLCanvas(executor, profile, flipY, msaa, true);
canvas.setAnimator(animator);
canvas.dispose();

```
On my machines it happened sometimes, not always. Need some good lucks, I guess :)
**Screenshots**
![image](https://github.com/husker-dev/openglfx/assets/94328752/ace419a8-c61c-4f17-aa5c-c24dd1033587)

**Environment:**
 - OS: Windows 11
 - openglfx version: 4.0.5

**Comment by husker-dev** [comment]
Check the new release 4.1.0.
If the problem is not solved, then reopen the issue
