### ISSUE TITLE
Example code generator is no longer available

### ISSUE THREAD

**Issue by carlislefox** [husker-dev/openglfx#83]
This library looks like exactly what I have been looking for, but it is impenetrable without any code examples.

I've just spent a few hours getting my JavaFX project set up and working with the LibGDX backend (learning about module exports, isn't java fun) only to hit an issue where it appears there are no Application instances in the LibGDXExecutor.

I am sure there is a good reason for this, and something I should be doing, but the example code generator link is dead so with no examples or documentation I'm at somewhat of a loss...

**Comment by husker-dev** [comment]
Forgot to pay for the domain :) 
Now it should work.

---

`LibGDXExecutor` is a "bridge" object between LibGDX and openglfx. It doesn't contain Application. 
You should think of openglfx as a node, not an window or application.

And you should use it like that:
```java
// 1. Create JavaFX window as always
// ...

// 2. Create GLCanvas with the default LibGDXExecutor
GLCanvas canvas = new GLCanvas(LibGDXExecutor.LIBGDX_MODULE);

// 2. Or with some libgdx configuration
OGLFXApplicationConfiguration config = new OGLFXApplicationConfiguration();
config.<...>
GLCanvas canvas = new GLCanvas(LibGDXExecutor.LIBGDX_MODULE(config));

// 3. Then add canvas to the JavaFX Scene
stage.setScene(new Scene(canvas));

```
---
Also note - don't use openglfx+JavaFX in a game for UI - it has some performance overhead. 
The best option is to use it as an editor.
