### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by brumhard** [husker-dev/openglfx#85]
**I have a question***

Hi there, I'm trying to use this project for libgdx. Since the latest master version contains some bugfixes for that, it would be awesome, if you could release a new version 🙏🏻

**Comment by husker-dev** [comment]
I just got free from another project. 
I will try to do my best to finish the current version and release it soon.

**Comment by husker-dev** [comment]
I have released a new version `4.1.0` and described some things about LibGDX in README.md
