### ISSUE TITLE
Canvas is not dirtying itself

### ISSUE THREAD

**Issue by yetyman** [husker-dev/openglfx#86]
**Suddenly the canvas has stopped refreshing its image, I assume this is from a lack of dirtying the render area**
`canvas = new GLCanvas(LWJGL_MODULE, GLProfile.Core, true, msaa, false);` //msaa is 8 here.

**To Reproduce**
I have no idea how to reproduce this issue. I have been using this library for over a year and my current code version has been working correctly for months, I have not seen this issue before. I can tell you the symptoms I am seeing.

1. Overlapping Javafx controls are dirtying and redrawing their regions with the updated render showing behind them, so this seems to be an issue with dirtying and redrawing rather than with my write to the default frame buffer.

2. On occasion it will still refresh itself. This is not limited by the time my renders take, my renders take place in a separate thread and are triple buffered. Here the data is only blitted. When this issue occurs, the fps value from openglfx becomes very low and very inconsistent
  
      a. as an example here I have printed the GlRenderEvent::fps once every 20 seconds for a while: 3,4,8,1,2,4,1,3,3,7,2,1....
      This fps read out ranges between 1-13 and steadily stays in that range for several minutes, though there are definitely spans of minutes where no redraw occurs so this may not correspond to visible renders or may just never say 0 when a render occurs to be able to print the value, 
      b. These FPS seem odd for just a blit to the default fbo presented by [NVDXInteropCanvasImpl.kt](https://github.com/husker-dev/openglfx/blob/master/core/src/main/kotlin/com/huskerdev/openglfx/canvas/implementations/NVDXInteropCanvasImpl.kt)

3. Nothing I am affecting is changing the issue, in the pasted video I am resizing the canvas along with my own render buffers. One good render comes out of each reshape but still is frozen outside of that one or very rare redraws. The issue remains.

**Screenshots**

https://github.com/user-attachments/assets/060ba3eb-ef3b-41cc-9217-a675f7a5e6e9

https://github.com/user-attachments/assets/10243bee-43c2-4f30-bf8d-6b5462410cbc

**Environment:**
 - OS: Windows
 - openglfx version: 4.0.5

**Comment by yetyman** [comment]
I am realizing that this may be related to my calls to canvas.repaint() as that invokes the dirtying of the node. That invocation is in fact on my background render thread, so it is tied to render speed. 

My render speed is in fact higher than the render rate it is achieving on being dirtied, so a mystery remains, but i will attempt to use the Animator class and hope this issue does not occur again.

**Comment by husker-dev** [comment]
Check the new release `4.1.0`.
If the problem is not solved, then reopen the issue
