### ISSUE TITLE
Openglfx com.sun.prism.d3d  conflicts with javafx-graphics/com.sun.prism.d3d 

### ISSUE THREAD

**Issue by RealThanhpv** [husker-dev/openglfx#87]
**Describe the bug**
com.sun.prism.d3d is provided by both openglfx and javafx-graphics

**To Reproduce**
[N/A]

**Screenshots**
![image](https://github.com/user-attachments/assets/1fcec868-d1aa-4bfa-a675-bfec91bb3542)

**Environment:**
 - OS: [Windows/Mac]
 - openglfx version: [4.1.1]

**Comment by husker-dev** [comment]
Yes, openglfx contains JavaFX packages to access some package-private fields without reflection.
With a modular system, there is a choice of two evils - adding reflection openings or packages.

I don't know much about modules, so I probably won't be able to help

**Comment by RealThanhpv** [comment]
Why not use reflection or possibly change the package name.  It is always used with JavaFX, I don't think conflicting with its names is a good idea. Is there very good reason not using reflection?

**Comment by husker-dev** [comment]
Reflection creates a lot of problems with modules, as well as with compilation using GraalVM (Gluon). Therefore, in the current version, I tried to replace any reflection with JNI, or in such tricks with packages.

I can't just "rename" the package. It will lose access to JavaFX's package-private fields/classes/functions.

I understand that this isn't the most elegant option. I'll see how can I avoid it

**Comment by phamvanthanh** [comment]
I can confirm that I build the version 4.0.5 to native image with graalvm without problems

**Comment by RealThanhpv** [comment]
I can confirm that I built the version 4.0.5 to native image with Graalvm without problems.

**Comment by husker-dev** [comment]
I have completely removed the use of javafx packages. 
There will be a fix release this weekend.

**Comment by husker-dev** [comment]
Released 4.1.4 - removed package-hacks and added `module-info`
