### ISSUE TITLE
Crash on macOS since 4.1.3

### ISSUE THREAD

**Issue by webner** [husker-dev/openglfx#88]
**Describe the bug**
The openglfx-example crashes with version 4.1.3 - 4.1.5 with following problem report:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               java [24015]
Path:                  /Library/Java/JavaVirtualMachines/graalvm-jdk-22.0.2+9.1/Contents/Home/bin/java
Identifier:            java
Version:               22.0.2 (9)
Code Type:             ARM-64 (Native)
Parent Process:        idea [14636]
Responsible:           idea [14636]
User ID:               501

Date/Time:             2024-12-17 16:39:56.5096 +0100
OS Version:            macOS 15.2 (24C101)
Report Version:        12
Anonymous UUID:        1A446065-89D4-E399-D820-6552F26D4A43

Sleep/Wake UUID:       B17CABB6-9689-4CD9-99F3-83ECCEDD0A56

Time Awake Since Boot: 180000 seconds
Time Since Wake:       116208 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000003e0504af000
Exception Codes:       0x0000000000000001, 0x000003e0504af000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   java [24015]

VM Region Info: 0x3e0504af000 is not in any region.  Bytes after previous region: 256569345  Bytes before following region: 101291161620480
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      VM_ALLOCATE               3e040000000-3e041000000  [ 16.0M] ---/rwx SM=NUL  
--->  GAP OF 0x5c1fbf000000 BYTES
      MALLOC_NANO              600000000000-600020000000 [512.0M] rw-/rwx SM=PRV  

Application Specific Information:
abort() called

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x19bfaf720 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x19bfe7f70 pthread_kill + 288
2   libsystem_c.dylib             	       0x19bef4908 abort + 128
3   libjvm.dylib                  	       0x101f5e99c os::abort(bool, void*, void const*) + 56
4   libjvm.dylib                  	       0x1021249fc VMError::report_and_die(int, char const*, char const*, char*, Thread*, unsigned char*, void*, void*, char const*, int, unsigned long) + 2364
5   libjvm.dylib                  	       0x1021240c0 VMError::report_and_die(Thread*, unsigned int, unsigned char*, void*, void*, char const*, ...) + 72
6   libjvm.dylib                  	       0x102124d94 VMError::report_and_die(Thread*, unsigned int, unsigned char*, void*, void*) + 36
7   libjvm.dylib                  	       0x102003538 JVM_handle_bsd_signal + 464
8   libsystem_platform.dylib      	       0x19c01ee04 _sigtramp + 56
9   1734449996220#com-huskerdev-grapl-gl-native-lib-2.3.0.dylib	       0x10e7ab538 getContextDetails(GLDetails*) + 44
10  1734449996220#com-huskerdev-grapl-gl-native-lib-2.3.0.dylib	       0x10e7ab484 Java_com_huskerdev_grapl_gl_platforms_macos_CGLContext_nGetCurrentContext + 48

**To Reproduce**
Update openglfx to version 4.1.3 in the example project and run it on macOS with arm64 hardware.

**Environment:**
 - OS: macOS arm64
 - openglfx version: 4.1.3 - 4.1.5

**Comment by webner** [comment]
This seems to be the place where it crashes:
https://github.com/husker-dev/openglfx/compare/4.1.2...4.1.3#diff-3bfa56d8e1f27550e082d056fff08cc5c3175c6d91bebaec887aa7a1d46a8c4aR64

**Comment by husker-dev** [comment]
Yes, I know what the problem is. It was one of the fixes in the latest versions that broke macOS. 
I'll release a new hotfix in 15-20 minutes.

**Comment by husker-dev** [comment]
Sent verision 4.1.6 to maven, will be available in a few minutes.
Thanks for reporting :)
