### ISSUE TITLE
Add option to set `GLProfile` in `LibGDXCanvas`

### ISSUE THREAD

**Issue by brumhard** [husker-dev/openglfx#89]
Hi there,
some of LibGDX's default shaders still don't work in `GLProfile.Core` (see https://github.com/libgdx/libgdx/issues/6897 and related items).
In my case e.g. the `SpritBatch` default shader breaks.
Therefore, it would be awesome if you could make the `GLProfile` an argument to the `LibGDXCanvas`.
Maybe it would even be an option to set the default to `GLProfile.Compatibility` just for LibGDX.
Thanks for your great work 🙏🏻

**Comment by husker-dev** [comment]
Thanks for reporting the issue!  
I'll publish a fix in the next 30 minutes.

I'd be very happy if you report other issues with LibGDX + openglfx if you encounter them. 
This module was more of an experiment, so I didn't test it thoroughly.

**Comment by husker-dev** [comment]
Added GLProfile setting in the version 4.1.7
